title: Monlight
description: Self-hosted, lightweight monitoring stack
theme: just-the-docs

color_scheme: dark

search_enabled: true
search:
  heading_level: 2
  previews: 3
  preview_words_before: 5
  preview_words_after: 10
  button: true
  focus_shortcut_key: "k"

heading_anchors: true

aux_links:
  GitHub:
    - "https://github.com/mattmezza/monlight"
aux_links_new_tab: true

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/mattmezza/monlight"
gh_edit_branch: "main"
gh_edit_source: "docs"
gh_edit_view_mode: "tree"

callouts:
  warning:
    title: Warning
    color: red
  note:
    title: Note
    color: blue
  tip:
    title: Tip
    color: green
  important:
    title: Important
    color: yellow

exclude:
  - Gemfile.lock
